// utils/ImageMapper.js

export const imageMap = {
  servicios: {
    'arreglo-y-diseo-de-barba': require('../assets/Servicios/Arreglo&DiseñoBarba.jpg'),
    'coloracin-de-cabello': require('../assets/Servicios/Coloracion.jpg'),
    'corte-de-cabello-masculino': require('../assets/Servicios/CorteCabello.jpg'),
    'corte-de-cabello-general': require('../assets/Servicios/CorteCabello.jpg'), 
    'criolipolisis': require('../assets/Servicios/Criolipolisis.jpg'),
    'depilacin-lser-shr-sesin': require('../assets/Servicios/DepilacionDefinitiva.jpg'),
    'despigmentacin-facial': require('../assets/Servicios/Despigmentacion.jpg'),
    'diseo-y-delineado-de-cejas': require('../assets/Servicios/Diseño&Delineado.png'),
    'eliminacin-de-celulitis': require('../assets/Servicios/EliminacionCelulitis.jpg'),
    'eliminacin-de-tatuajes-sesin': require('../assets/Servicios/EliminacionTatuajes.jpg'),
    'hidradermoabrasin': require('../assets/Servicios/Hidradermoabrasion.jpg'),
    'hifu-facial': require('../assets/Servicios/Hifu.jpg'),
    'hollywood-peel': require('../assets/Servicios/HollywoodPeel.jpg'),
    'levantamiento-de-glteos': require('../assets/Servicios/LevantamientoGluteos.jpg'),
    'limpieza-facial': require('../assets/Servicios/LimpiezaFacial.jpg'),
    'lipo-sin-ciruga': require('../assets/Servicios/LipoSinCirugia.jpg'),
    'maderoterapia': require('../assets/Servicios/Maderoterapia.jpg'),
    'masaje-relajante': require('../assets/Servicios/MasajeRelajante.jpg'),
    'microdermoabrasin': require('../assets/Servicios/Microdermoabrasion.jpg'),
    'perfilado-de-cejas': require('../assets/Servicios/PerfiladoCejas.jpg'),
    'radiofrecuencia-facial': require('../assets/Servicios/Radiofrecuencia Facial.jpg'),
    'rostro-hombre': require('../assets/Servicios/Rostro Hombre.jpg'),
    'rostro-mujer': require('../assets/Servicios/Rostro Mujer.jpg'),
    'sculpsure': require('../assets/Servicios/Sculpsure.jpg'),
    'tratamiento-capilar': require('../assets/Servicios/TratamientoCapilar.jpg'),
    'paquete-reafirmante' : require('../assets/Servicios/Rostro Mujer.jpg'),
  },
  productos: {
    '2-meses-blsamo-clsico-2oz--minoxidil--biotina--queratina': require('../assets/Productos/2 MesesBálsamoClásico2oz-Minoxidil+Biotina&Queratina.png'),
    '2-meses-blsamo-clsico-2oz--minoxidil--biotina--queratina-kit': require('../assets/Productos/2MesesBálsamoClásico2oz-Minoxidil+Biotina&Queratina.png'),
    '2-meses-blsamo-clsico-2oz--jabn-carbn-activado-100gr-kit': require('../assets/Productos/2MesesBálsamoClásico2oz+JabónCarbónActivado100gr.png'),
    '2-meses-gel-blsamo-de-crecimiento-2oz--minoxidil-5--biotina--queratina-kit': require('../assets/Productos/2MesesGelBálsamodeCrecimiento2oz-Minoxidil5%+Biotina&Queratina.png'),
    'aceite-para-barba-black-jack-50ml--bergamota--jojoba--suaviza': require('../assets/Productos/AceiteparaBarbaBlackJack50ml-Bergamota+Jojoba+Suaviza.png'),
    'aceite-para-barba-royal-barber-60ml--hidratacin--acondiciona': require('../assets/Productos/AceiteparaBarbaRoyalBarber60ml-Hidratación+Acondiciona.png'),
    'ace-pomade-supreme-grip-4oz--biotina--queratina--cafena': require('../assets/Productos/AcePomadeSupremeGrip4oz-Biotina+Queratina+Cafeína.png'),
    'blsamo-clsico-de-crecimiento-de-barba-y-bigote-5-minoxidil---2oz60ml-biotina--queratina--vitaminas': require('../assets/Productos/BálsamoClásicodeCrecimientodeBarbayBigote5%Minoxidil-2oz-60ml.png'),
    'blsamo-negro-para-barba-27oz--cubre-canas--pigmento-mineral-100-natural--estiliza--moldea': require('../assets/Productos/BálsamoNegroparaBarba2.7oz-Cubrecanas+PigmentoMineral100%Natural.png'),
    'cera-de-abeja-royal-barber-2oz--ingredientes-100-naturales': require('../assets/Productos/CeradeAbejaRoyalBarber2oz-Ingredientes100%Naturales.png'),
    'cera-hbrida-para-cabello-y-barba-32oz--acabado-natural--fijacin-media': require('../assets/Productos/CeraHíbridaparaCabelloyBarba4oz-Acabado Natural.png'),
    'cera-hbrida-para-cabello-y-barba-4oz--acabado-natural--fijacin-media': require('../assets/Productos/CeraHíbridaparaCabelloyBarba4oz-AcabadoNatural+FijaciónMedia.png'),
    'cera-hbrida-para-cabello-y-barba-32oz-acabado-natural-fijacin-media': require('../assets/Productos/CeraHíbridaparaCabelloyBarba32oz-AcabadoNatural+FijaciónMedia.png'),
    'crema-de-afeitar-8oz--protege-la-piel-de-la-irritacin-y-escozor': require('../assets/Productos/CremadeAfeitar8oz-Protegelapieldelairritaciónyescozor.png'),
    'desinfectante-y-limpiador-de-brochas-125ml--desinfecta-y-cuida-brochas-cepillos--peines': require('../assets/Productos/DesinfectanteyLimpiadordeBrochas125ml-DesinfectayCuidaBrochas-Cepillos.png'),
    'exfoliador-facial-de-cascara-de-nuez-4oz--limpieza-natural': require('../assets/Productos/ExfoliadorFacialdeCascaradeNuez4oz-LimpiezaNatural.png'),
    'gel-blsamo-de-crecimiento-2oz60ml-minoxidil-5--biotina--queratina--vitaminas': require('../assets/Productos/GelBálsamodeCrecimiento2oz-60mlMinoxidil5%+Biotina+Queratina.png'),
    'gel-clsico-fortificante-6oz--previene-cada-de-cabello': require('../assets/Productos/GelClásicoFortificante6oz-PrevieneCaídadeCabello.png'),
    'gel-deslizante-para-afeitar-6oz--reduce-irritacin--visibilidad-total': require('../assets/Productos/GelDeslizanteparaAfeitar6oz-ReduceIrritación+VisibilidadTotal.png'),
    'gel-pomada-4oz--ceras-de-pomada-en-consistencia-gel--brillo-sutil--fijacion-natural': require('../assets/Productos/GelPomada4oz-CerasdePomadaenConsistenciaGel+BrilloSutil+FijacionNatural.png'),
    'gomero-navajero-mel-bros-co--tpe-grado-farmaceutico': require('../assets/Productos/GomeroNavajeroMelBrosCo-TPEGradoFarmaceutico.png'),
    'green-balm-crecimiento-de-barba-y-bigote-2oz60ml-alga-marinas--biotina--regaliz--queratina': require('../assets/Productos/GreenBalmCrecimientodeBarbayBigote2oz-60mlAlgaMarinas.png'),
    'hair-wash-shampoo-de-limpieza-profunda-4oz--elimina-toxinas': require('../assets/Productos/HairWashShampoodeLimpiezaProfunda4oz-EliminaToxinas.png'),
    'jabn-de-carbn-activado-170gr--detox-y-limpieza': require('../assets/Productos/JabóndeCarbónActivado170gr-DetoxyLimpieza.png'),
    'jabn-para-afeitar-con-aroma-353oz--hidratante--afeitado-suave': require('../assets/Productos/JabónparaAfeitarconAroma3.53oz-Hidratante+AfeitadoSuave.png'),
    'jabn-para-afeitar-sin-aroma-353oz--hidratante--afeitado-suave': require('../assets/Productos/JabónparaAfeitarsinAroma3.53oz-Hidratante+AfeitadoSuave.png'),
    'kit-cuidado-de-barba': require('../assets/Productos/KitCuidadodeBarba.png'),
    'kit-de-afeitado': require('../assets/Productos/KitdeAfeitado.png'),
    'mascarilla-facial-wake-up-revitalizante-27oz': require('../assets/Productos/MascarillaFacialWakeUpRevitalizante2.7oz.png'),
    'ocean-salt-shampoo-8oz': require('../assets/Productos/OCEANSALTSHAMPOO8OZ.png'),
    'pomada-base-aceite-32oz--formula-no-grasosa--controla-frizz': require('../assets/Productos/PomadaBaseAceite4oz-FormulaNoGrasosa+ControlaFrizz.png'),
    'pomada-base-aceite-32oz-formula-no-grasosa': require('../assets/Productos/PomadaBaseAceite32oz-FormulaNoGrasosa.png'),
    'pomada-base-aceite-royal-barber-4oz--no-grasoso-y-fcil-lavado--sin-caja': require('../assets/Productos/PomadaBaseAceiteRoyalBarber4oz-Nograsosoyfácil.png'),
    'pomada-base-agua-royal-barber-4oz--aceite-de-cedro--formula-alemana--activos-y-ceras-naturales': require('../assets/Productos/PomadaBaseAguaRoyalBarber4oz-AceitedeCedro+FormulaAlemana.png'),
    'pomada-clasica-4oz--base-agua--media-fijacin': require('../assets/Productos/PomadaClasica4oz-BaseAgua+Mediafijación.png'),
    'pomada-clsica-32oz--base-agua--media-fijacin': require('../assets/Productos/PomadaClásica32oz-BaseAgua+MediaFijación.png'),
    'pomada-mate-4oz--acabado-satinado--extra-fijacin': require('../assets/Productos/PomadaMate4oz-AcabadoSatinado+ExtraFijación.png'),
    'pomada-mate-32oz--acabado-satinado--extra-fijacin': require('../assets/Productos/PomadaMate32oz-AcabadoSatinadoExtraFijación.png'),
    'pomada-mate-royal-barber-4oz--efecto-mate': require('../assets/Productos/PomadaMateRoyalBarber4oz-EfectoMate.png'),
    'pomada-negra-4oz118ml-oscurece-canas': require('../assets/Productos/PomadaNegra4oz-118ml-OscureceCanas.png'),
    'pomada-original-4oz--base-agua--extra-fijacin': require('../assets/Productos/PomadaOriginal4oz-BaseAgua+ExtraFijación.png'),
    'pomada-original-32oz--base-agua--extra-fijacin': require('../assets/Productos/PomadaOriginal32oz-BaseAgua+ExtraFijación.png'),
    'reelance-cera-hbrida-120ml': require('../assets/Productos/ReelanceCeraHíbrida120ml.png'),
    'reelance-crecimiento-de-cejas-60ml': require('../assets/Productos/ReelanceCrecimientodeCejas60ml.png'),
    'reelance-crecimiento-pestaas-6ml': require('../assets/Productos/ReelanceCrecimientoPestañas6ml.png'),
    'reelance-locin-hombre-60-ml': require('../assets/Productos/ReelanceLociónHombre60ml.png'),
    'reelance-locin-mujer-60ml': require('../assets/Productos/ReelanceLociónMujer60ml.png'),
    'reelance-shampoo-hombre-120ml': require('../assets/Productos/ReelanceShampooHombre120ml.png'),
    'reelance-shampoo-mujer-120ml': require('../assets/Productos/ReelanceShampooMujer120ml.png'),
    'reelance-tratamiento-restaurador-120ml': require('../assets/Productos/ReelanceTratamientoRestaurador120ml.png'),
    'ron-de-baha-royal-barber-100-ml--cierra-poros--tonifica-piel': require('../assets/Productos/RondeBahíaRoyalBarber100ml-CierraPoros+TonificaPiel.png'),
    'set-viajero-de-pomadas-de-2oz-5-piezas': require('../assets/Productos/SetViajerodePomadasde2oz(5Piezas).png'),
    'shampoo-de-barba-8oz--aceites-esenciales--reduce-picazn-y-resequedad': require('../assets/Productos/ShampoodeBarba8oz-AceitesEsenciales+Reducepicazónyresequedad.png'),
    'shampoo-estimulante-8oz-230ml-anti-cada': require('../assets/Productos/ShampooEstimulante8oz-230ml-AntiCaída.png'),
    'shampoo-estimulante-8oz230ml--anti-cada--algas-marinas': require('../assets/Productos/ShampooEstimulante8oz-230ml-AntiCaída+AlgasMarinas.png'),
    'soothing-after-shave-6oz--crema-reparadora--antiinflamatoria': require('../assets/Productos/SoothingAfterShave6oz-CremaReparadora&Antiinflamatoria.png'),
    'tratamiento-anti-edad-2oz--cido-hialurnico-y-extracto-pepino': require('../assets/Productos/TratamientoAntiEdad2oz-ÁcidoHialurónicoyExtractoPepino.png'),
    'aceite-pre-afeitado-royal-barber-60ml--ctricos--elimina-irritacin-del-afeitado' : require('../assets/Productos/AcePomadeSupremeGrip4oz-Biotina+Queratina+Cafeína.png'),
    'pomada-base-aceite-4oz--formula-no-grasosa--controla-frizz' : require('../assets/Productos/PomadaBaseAceite4oz-FormulaNoGrasosa+ControlaFrizz.png')
  },

 // --- SECCIÓN DE SUCURSALES (CORREGIDA) ---
  sucursales: {
    'barbermusicspa-villahermosa-plaza-altabrisa': require('../assets/Sucursales/BarberMusicI.jpg'),
    'barbermusicspa-villahermosa-ii-plaza-las-americas': require('../assets/Sucursales/BarberMusicII.jpg'),
    'barbermusicspa-ciudad-del-carmen-plaza-zentralia': require('../assets/Sucursales/BarberMusicIII.jpg'),
    'musicspavillahermosa-mrida-plaza-altabrisa': require('../assets/Sucursales/Villahermosa.jpg'),
    'musicspavillahermosa-villahermosa-iii-plaza-altabrisa': require('../assets/Sucursales/VillahermosaIV.jpg'),
    'barbermusicspa-san-luis-potos-plaza-san-luis': require('../assets/Sucursales/Villahermosall.jpg'), // Corregido de II a ll
    'barbermusicspa-coatzacoalcos-plaza-forum': require('../assets/Sucursales/Villahermosalll.jpg'), // Corregido de III a lll
    'villahermosa-vii': require('../assets/Sucursales/VillahermosaVII.jpg'),
  },

  default: require('../assets/BarberMusicSpaNoFondo.png'),
};